[package]
name = "old-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decaf377 = { workspace = true }
penumbra-keys = { path = "../core/keys", default-features = false }
penumbra-shielded-pool = { path = "../core/component/shielded-pool/" }
penumbra-dex = { path = "../core/component/dex"}
rand_core = "0.6.4"

[dev-dependencies]
penumbra-proof-params = { path = "../crypto/proof-params", features = [
    "bundled-proving-keys",
    "download-proving-keys",
] }
