[package]
name = "old-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-keys = { path = "../core/keys", default-features = false }
penumbra-shielded-pool = { path = "../core/component/shielded-pool/" }
penumbra-dex = { path = "../core/component/dex"}
decaf377_v05 = { package = "decaf377", version = "0.5", features = ["r1cs"] }
decaf377 = { workspace = true }
once_cell = "1.19.0"
ark-serialize = "0.4.2"
ark-groth16 = "0.4.0"
ark-relations = "0.4.0"
ark-r1cs-std = "0.4.0"
ark-snark = "0.4.0"
ark-std = "0.4.0"
ark-ff = "0.4.2"
ark-ec = "0.4.2"
anyhow = "1.0.79"
rand_chacha = "0.3.1"
bech32 = "0.9.1"
sha2 = "0.10.8"

[dev-dependencies]
penumbra-governance = { path = "../core/component/governance", default-features = false }
penumbra-proof-params = { path = "../crypto/proof-params", features = [
    "bundled-proving-keys",
    "download-proving-keys",
] }
